// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: t.proto

package json

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the

type TE struct {
	A                    string            `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	B                    int64             `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
	C                    map[string]string `protobuf:"bytes,3,rep,name=C,proto3" json:"C,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	D                    []int64           `protobuf:"varint,4,rep,packed,name=D,proto3" json:"D,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TE) Reset()         { *m = TE{} }
func (m *TE) String() string { return proto.CompactTextString(m) }
func (*TE) ProtoMessage()    {}
func (*TE) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{0}
}
func (m *TE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TE.Unmarshal(m, b)
}
func (m *TE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TE.Marshal(b, m, deterministic)
}
func (m *TE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TE.Merge(m, src)
}
func (m *TE) XXX_Size() int {
	return xxx_messageInfo_TE.Size(m)
}
func (m *TE) XXX_DiscardUnknown() {
	xxx_messageInfo_TE.DiscardUnknown(m)
}

var xxx_messageInfo_TE proto.InternalMessageInfo

func (m *TE) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *TE) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *TE) GetC() map[string]string {
	if m != nil {
		return m.C
	}
	return nil
}

func (m *TE) GetD() []int64 {
	if m != nil {
		return m.D
	}
	return nil
}

type T struct {
	A                    string            `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	B                    int64             `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
	C                    map[string]string `protobuf:"bytes,3,rep,name=C,proto3" json:"C,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	D                    []int64           `protobuf:"varint,4,rep,packed,name=D,proto3" json:"D,omitempty"`
	Extra                *TE               `protobuf:"bytes,5,opt,name=Extra,proto3" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *T) Reset()         { *m = T{} }
func (m *T) String() string { return proto.CompactTextString(m) }
func (*T) ProtoMessage()    {}
func (*T) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{1}
}
func (m *T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_T.Unmarshal(m, b)
}
func (m *T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_T.Marshal(b, m, deterministic)
}
func (m *T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_T.Merge(m, src)
}
func (m *T) XXX_Size() int {
	return xxx_messageInfo_T.Size(m)
}
func (m *T) XXX_DiscardUnknown() {
	xxx_messageInfo_T.DiscardUnknown(m)
}

var xxx_messageInfo_T proto.InternalMessageInfo

func (m *T) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *T) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *T) GetC() map[string]string {
	if m != nil {
		return m.C
	}
	return nil
}

func (m *T) GetD() []int64 {
	if m != nil {
		return m.D
	}
	return nil
}

func (m *T) GetExtra() *TE {
	if m != nil {
		return m.Extra
	}
	return nil
}

func init() {
	proto.RegisterType((*TE)(nil), "proto.TE")
	proto.RegisterMapType((map[string]string)(nil), "proto.TE.CEntry")
	proto.RegisterType((*T)(nil), "proto.T")
	proto.RegisterMapType((map[string]string)(nil), "proto.T.CEntry")
}

func init() { proto.RegisterFile("t.proto", fileDescriptor_ab95a3f7bbc9aa38) }

var fileDescriptor_ab95a3f7bbc9aa38 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x62, 0x2f, 0xd1, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x2d, 0x8c, 0x5c, 0x4c, 0x21, 0xae, 0x42, 0x3c,
	0x5c, 0x8c, 0x8e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x8c, 0x8e, 0x20, 0x9e, 0x93, 0x04,
	0x93, 0x02, 0xa3, 0x06, 0x73, 0x10, 0xa3, 0x93, 0x90, 0x1c, 0x17, 0xa3, 0xb3, 0x04, 0xb3, 0x02,
	0xb3, 0x06, 0xb7, 0x91, 0x00, 0x44, 0xb3, 0x5e, 0x88, 0xab, 0x9e, 0xb3, 0x6b, 0x5e, 0x49, 0x51,
	0x65, 0x10, 0xa3, 0x33, 0x48, 0xb5, 0x8b, 0x04, 0x8b, 0x02, 0x33, 0x48, 0xb5, 0x8b, 0x94, 0x09,
	0x17, 0x1b, 0x44, 0x4a, 0x48, 0x80, 0x8b, 0x39, 0x3b, 0xb5, 0x12, 0x6a, 0x2a, 0x88, 0x29, 0x24,
	0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x0a, 0x36, 0x9b, 0x33, 0x08, 0xc2, 0xb1, 0x62, 0xb2,
	0x60, 0x54, 0x5a, 0xcc, 0xc8, 0xc5, 0x18, 0x82, 0xd7, 0x15, 0xb2, 0x08, 0x57, 0xf0, 0xc3, 0x5c,
	0x81, 0xcb, 0x11, 0x42, 0xf2, 0x5c, 0xac, 0xae, 0x15, 0x25, 0x45, 0x89, 0x12, 0xac, 0x0a, 0x8c,
	0x1a, 0xdc, 0x46, 0x9c, 0x70, 0x67, 0x07, 0x41, 0xc4, 0xc9, 0x73, 0x65, 0x12, 0x1b, 0xd8, 0x18,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x14, 0x5f, 0x6e, 0x7e, 0x45, 0x01, 0x00, 0x00,
}
